server:
  port: 8180
spring:
  application:
    name: web-home
  zipkin:
    baseUrl: http://127.0.0.1:9411/
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
sample:
  zipkin:
    enabled: true